site_name: Py-ADTools
site_description: 'A Python toolkit for LLM-aided algorithm design, offering tools for code parsing, sandboxed execution, and evaluation.'
repo_url: https://github.com/RayZhhh/py-adtools
edit_uri: ""

docs_dir: source

theme:
  name: readthedocs
  highlightjs: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Core Modules:
    - Code Parsing: parsing.md
    - Sandbox Execution: sandbox.md
    - Code Evaluation: evaluator.md
    - Language Models: language_models.md
    - Auto-Eval Server: auto_server.md
